{% set version = "1.16.0" %}
{% set sha256 = "271dc42d0a7ab3bd311eefa4ba8fd19f99ec093cf5e9053426f358914c8983d6" %}

package:
  name: cub
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cub/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.15
    - make
  run_constrained:
    - thrust {{ version }}.*

test:
  commands:
    - test -e "$PREFIX"/include/cub/cub.cuh  # [not win]
    - test -e "$PREFIX"/lib/cmake/cub/cub-config.cmake  # [not win]
    - if not exist "%LIBRARY_INC%"\cub\cub.cuh exit 1  # [win]
    - if not exist "%LIBRARY_LIB%"\cmake\cub\cub-config.cmake  # [win]

about:
  home: https://github.com/NVIDIA/cub
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: |
    CUB is a flexible library of cooperative threadblock primitives and other utilities for CUDA
    kernel programming.
  description: |
    CUB provides state-of-the-art, reusable software components for every layer of the CUDA
    programming model:
    - Parallel primitives
      - Warp-wide "collective" primitives
        - Cooperative warp-wide prefix scan, reduction, etc.
        - Safely specialized for each underlying CUDA architecture
      - Block-wide "collective" primitives
        - Cooperative I/O, sort, scan, reduction, histogram, etc.
        - Compatible with arbitrary thread block sizes and types
      - Device-wide primitives
        - Parallel sort, prefix scan, reduction, histogram, etc.
        - Compatible with CUDA dynamic parallelism
    - Utilities
      - Fancy iterators
      - Thread and thread block I/O
      - PTX intrinsics
      - Device, kernel, and storage management
  doc_url: http://nvlabs.github.io/cub/
  dev_url: https://github.com/thrust/cub

extra:
  recipe-maintainers:
    - rongou
    - kkraus14
    - leofang
